package com.codetrex.cayroshop.utils;

public class Constants {

    public static final String PLEASE_WAIT = "Please wait";
    public static final String PREF_DEFAULT_STRING = "NA";
    public static final String CLOSE = "Close";
    public static final String NAME = "name";
    public static final String WISHLIST = "Wish List";
    public static final String OTP_ERROR = "Invalid OTP";
    public static final String EMAIL_ERROR = "Please enter email ID";
    public static final String FIRST_NAME_ERROR = "Please enter first name";
    public static final String LAST_NAME_ERROR = "Please enter last name";
    public static final String MOBILE_ERROR = "Please enter mobile number";
    public static final String PASSWORD_ERROR = "Please enter your password";
    public static final String CONVERT = "Convert";
    public static final String HOME = "Home";
    public static final String COUNTRY_ID = "90";
    public static final String SELECT_STATE = "Select state";
    public static final String SELECT_CITY = "Select city";
    public static final String USER_ADDRESS = "Please enter address";
    public static final String ERROR_PINCODE = "Please enter pincode";
    public static final String LATITUDE = "latitude";
    public static final String LONGITUDE = "longitude";
    public static final String DB_NAME = "suvek";
    public static final String NEW_MEMBER = "new_member";
    public static final String MOBILE = "mobile";
    public static final String VIDEO = "Videos";
    public static final String DAILY_TASK = "Today's Task";
    public static final String CATEGORY = "Category";
    public static final String FILTER = "Filter";
    public static final String MY_CART = "Cart";
    public static final String ADDRESS = "Address";
    public static final String REVIEW_ORDER = "Review order";
    public static final String PAYMENT_OPTIONS = "Payment option";
    public static final String PRODUCT_DETAIL = "Product detail";
    public static final String PRODUCTS = "Products";
    public static final String CART_VALUE = "cart_values";
    public static final String CATEGORY_ID = "category_id";
    public static final String APP_ICON_URL = "http://suvek.com/assets/images/logo.png";
    public static final String GROUP_ID = "group_id";
    public static final String VIDEO_DETAIL = "video_detail";
    public static final String REGISTRATION = "registration";
    public static final String USER = "user";
    public static final String USER_ID = "user_id";
    public static final String COUNT = "count";
    public static final String LOGIN = "login";
    public static final String INVALID_MSG = "Invalid credentials";
    public static final String ACTION_PAGE = "checkout";
    public static final String WISH_LIST_PAGE = "wishlist";
    public static final String AD_VIDEO = "video";
    public static final String TASK_1 = "1";
    public static final String TASK_2 = "2";
    public static final String TASK_3 = "3";
}
